# vars
:port = 8000
:root := (concat "http://localhost:" ":port")

# main route
GET :root

# echo route
POST :root/anneal
Content-Type: application/json
{
  "cities": [0,1,2],
  "distances": [[0,9,4],[5,0,6],[7,7,0]]
}

# test serialization
GET :root/test

# cities: Vec<usize>,
# distances: Vec<Vec<f64>>,